package com.midco.rota.model;

import java.math.BigDecimal;
import java.time.DayOfWeek;
import java.time.LocalDate;
import java.time.LocalTime;

import com.midco.rota.util.ShiftType;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * Entity mapping for rota_feeder table
 * This table stores both Auto-generated (OptaPlanner) and Manual (user-corrected) shift assignments
 */
@Entity
@Table(name = "rota_feeder")
public class RotaFeeder {
    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    private String region;
    
    private String location;
    
    @Enumerated(EnumType.STRING)
    @Column(name = "shift_type")
    private ShiftType shiftType;
    
    @Enumerated(EnumType.STRING)
    private DayOfWeek day;
    
    @Column(name = "shift_start")
    private LocalDate shiftStart;
    
    @Column(name = "shift_end")
    private LocalDate shiftEnd;
    
    private BigDecimal hours;
    
    // ✅ CRITICAL FIELD: Distinguishes Auto (OptaPlanner) vs Manual (user corrected)
    @Column(name = "emp_source")
    private String empSource; // "Auto" or "Manual"
    
    @Column(name = "first_name")
    private String firstName;
    
    @Column(name = "last_name")
    private String lastName;
    
    @Column(name = "week")
    private String week; // Week identifier (e.g., "2024-W44")
    
//    @Column(name = "start_time")
//    private LocalTime startTime;
//    
//    @Column(name = "end_time")
//    private LocalTime endTime;
    
    // Constructors
    public RotaFeeder() {
    }
    
    // Helper methods
    public String getEmployeeName() {
        if (firstName == null && lastName == null) {
            return "UNASSIGNED";
        }
        return (firstName != null ? firstName : "") + " " + (lastName != null ? lastName : "");
    }
    
    public boolean isAutoGenerated() {
        return "Auto".equalsIgnoreCase(empSource);
    }
    
    public boolean isManualCorrection() {
        return "Manual".equalsIgnoreCase(empSource);
    }
    
    public boolean isUnassigned() {
        return firstName == null && lastName == null;
    }
    
    // Getters and Setters
    public Long getId() {
        return id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    public String getRegion() {
        return region;
    }
    
    public void setRegion(String region) {
        this.region = region;
    }
    
    public String getLocation() {
        return location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    
    public ShiftType getShiftType() {
        return shiftType;
    }
    
    public void setShiftType(ShiftType shiftType) {
        this.shiftType = shiftType;
    }
    
    public DayOfWeek getDay() {
        return day;
    }
    
    public void setDay(DayOfWeek day) {
        this.day = day;
    }
    
    public LocalDate getShiftStart() {
        return shiftStart;
    }
    
    public void setShiftStart(LocalDate shiftStart) {
        this.shiftStart = shiftStart;
    }
    
    public LocalDate getShiftEnd() {
        return shiftEnd;
    }
    
    public void setShiftEnd(LocalDate shiftEnd) {
        this.shiftEnd = shiftEnd;
    }
    
    public BigDecimal getHours() {
        return hours;
    }
    
    public void setHours(BigDecimal hours) {
        this.hours = hours;
    }
    
    public String getEmpSource() {
        return empSource;
    }
    
    public void setEmpSource(String empSource) {
        this.empSource = empSource;
    }
    
    public String getFirstName() {
        return firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    
    public String getLastName() {
        return lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    
    public String getWeek() {
        return week;
    }
    
    public void setWeek(String week) {
        this.week = week;
    }
    
//    public LocalTime getStartTime() {
//        return startTime;
//    }
    
//    public void setStartTime(LocalTime startTime) {
//        this.startTime = startTime;
//    }
    
//    public LocalTime getEndTime() {
//        return endTime;
//    }
//    
//    public void setEndTime(LocalTime endTime) {
//        this.endTime = endTime;
//    }
    
    @Override
    public String toString() {
        return "RotaFeeder{" +
                "id=" + id +
                ", location='" + location + '\'' +
                ", shiftType=" + shiftType +
                ", day=" + day +
                ", shiftStart=" + shiftStart +
                ", empSource='" + empSource + '\'' +
                ", employee='" + getEmployeeName() + '\'' +
                ", hours=" + hours +
                '}';
    }
}