package com.midco.rota.repository;

import java.time.LocalDate;
import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import com.midco.rota.model.RotaFeeder;

/**
 * Repository for accessing rota_feeder table
 * Used to extract corrections by comparing Auto vs Manual entries
 */
@Repository
public interface RotaFeederRepository extends JpaRepository<RotaFeeder, Long> {
    
    // Find by emp_source (Auto or Manual)
    List<RotaFeeder> findByEmpSource(String empSource);
    
    // Find shifts in date range
    List<RotaFeeder> findByShiftStartBetween(LocalDate startDate, LocalDate endDate);
    
    // Find by emp_source and date range
    @Query("SELECT rf FROM RotaFeeder rf WHERE rf.empSource = :empSource AND rf.shiftStart BETWEEN :startDate AND :endDate")
    List<RotaFeeder> findByEmpSourceAndDateRange(@Param("empSource") String empSource, 
                                                  @Param("startDate") LocalDate startDate, 
                                                  @Param("endDate") LocalDate endDate);
    
    // Find manual corrections after a date
    @Query("SELECT rf FROM RotaFeeder rf WHERE rf.empSource = 'Manual' AND rf.shiftStart >= :startDate")
    List<RotaFeeder> findManualCorrectionsAfter(@Param("startDate") LocalDate startDate);
    
    // Find auto-generated after a date
    @Query("SELECT rf FROM RotaFeeder rf WHERE rf.empSource = 'Auto' AND rf.shiftStart >= :startDate")
    List<RotaFeeder> findAutoGeneratedAfter(@Param("startDate") LocalDate startDate);
    
    // Find by location
    List<RotaFeeder> findByLocation(String location);
    
    // Find by week identifier
    List<RotaFeeder> findByWeek(String week);
    
    // Find by location and week
    List<RotaFeeder> findByLocationAndWeek(String location, String week);
    
    // Find by employee name
    List<RotaFeeder> findByFirstNameAndLastName(String firstName, String lastName);
    
    // Find unassigned shifts (no employee name)
    @Query("SELECT rf FROM RotaFeeder rf WHERE rf.firstName IS NULL AND rf.lastName IS NULL")
    List<RotaFeeder> findUnassignedShifts();
    
    // Count by emp_source
    Long countByEmpSource(String empSource);
    
    // Count by emp_source and date range
    @Query("SELECT COUNT(rf) FROM RotaFeeder rf WHERE rf.empSource = :empSource AND rf.shiftStart BETWEEN :startDate AND :endDate")
    Long countByEmpSourceAndDateRange(@Param("empSource") String empSource, 
                                      @Param("startDate") LocalDate startDate, 
                                      @Param("endDate") LocalDate endDate);
    
    // Get statistics by location
    @Query("SELECT rf.location, rf.empSource, COUNT(rf) FROM RotaFeeder rf " +
           "WHERE rf.shiftStart BETWEEN :startDate AND :endDate " +
           "GROUP BY rf.location, rf.empSource ORDER BY rf.location, rf.empSource")
    List<Object[]> getStatsByLocation(@Param("startDate") LocalDate startDate, 
                                     @Param("endDate") LocalDate endDate);
    
    // Delete by date (for cleanup)
    void deleteByShiftStartBefore(LocalDate date);
}