-- V021: region + service_location master (from People Planner/Mobizio export + region-code mapping).
-- Re-runnable: recreates/refreshes the two reference tables. No FKs added to existing tables yet
-- (dropdowns are sourced from here; employee/shift_template columns stay strings per the agreed approach).

CREATE TABLE IF NOT EXISTS region (
  code varchar(10) PRIMARY KEY,
  name varchar(100) NOT NULL,
  staffrota_region varchar(30),            -- operating region the solver uses; NULL = not operated
  active boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS service_location (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  external_id varchar(40) UNIQUE NOT NULL,  -- People Planner external id, e.g. 01-0080
  region_code varchar(10) NOT NULL REFERENCES region(code),
  region_name varchar(100) NOT NULL,
  staffrota_region varchar(30),            -- denormalised for dropdown filtering by operating region
  service_id varchar(20) NOT NULL,          -- property id (= cf_db.matching_config.property_identifier)
  name varchar(200) NOT NULL,               -- canonical service name (from PP/Mobizio)
  mobizio_id varchar(40),
  active boolean NOT NULL DEFAULT true
);

TRUNCATE service_location;
TRUNCATE region CASCADE;

INSERT INTO region (code, name, staffrota_region) VALUES
  ('01', 'Barnet', 'BARNET'),
  ('05', 'Bracknell Forest', NULL),
  ('08', 'Buckinghamshire', 'BUCKS'),
  ('10', 'Cambridgeshire', NULL),
  ('12', 'Cornwall', 'CORNWALL'),
  ('15', 'Harare', NULL),
  ('22', 'Hertfordshire', 'HERTFORDSHIRE'),
  ('25', 'Gloucestershire', 'GLOUCOXF'),
  ('29', 'Johannesburg', NULL),
  ('36', 'Kent', 'KENT'),
  ('43', 'Lesotho Office', NULL),
  ('50', 'London', NULL),
  ('57', 'Manchester', 'MANCHESTER'),
  ('64', 'Milton Keynes', NULL),
  ('66', 'Southampton', NULL),
  ('71', 'Northamptonshire', 'NORTHANTS'),
  ('72', 'Nottingham', NULL),
  ('78', 'Peterborough', NULL),
  ('80', 'Luton', NULL),
  ('82', 'Oxfordshire', 'GLOUCOXF'),
  ('84', 'Barnsley', NULL);

INSERT INTO service_location (external_id, region_code, region_name, staffrota_region, service_id, name, mobizio_id) VALUES
  ('01-0155', '01', 'Barnet', 'BARNET', '0155', '1 Riverdale Lodge', '2-1157'),
  ('01-0089', '01', 'Barnet', 'BARNET', '0089', '17 First Avenue', '2-8'),
  ('01-0090', '01', 'Barnet', 'BARNET', '0090', '17A First Avenue', '2-1678'),
  ('01-0213', '01', 'Barnet', 'BARNET', '0213', '2 Golderton Flat', '2-1395'),
  ('01-0111', '01', 'Barnet', 'BARNET', '0111', '20 Glebe Crescent', '2-9'),
  ('01-0082', '01', 'Barnet', 'BARNET', '0082', '29 Edgeworth Close', '2-1418'),
  ('01-0144', '01', 'Barnet', 'BARNET', '0144', '3 Highfields Avenue', '2-1313'),
  ('01-0122', '01', 'Barnet', 'BARNET', '0122', '35 Golders Rise', '2-2'),
  ('01-0050', '01', 'Barnet', 'BARNET', '0050', '4 Audley Road', '2-1399'),
  ('01-0177', '01', 'Barnet', 'BARNET', '0177', '57 Sturgess Avenue', '2-10'),
  ('01-0212', '01', 'Barnet', 'BARNET', '0212', '61 Victoria Road', '2-1419'),
  ('01-0056', '01', 'Barnet', 'BARNET', '0056', '9 Claydon House', '2-1102'),
  ('01-0045', '01', 'Barnet', 'BARNET', '0045', 'Audley Rd No.134 Flat 2', '2-26'),
  ('01-0044', '01', 'Barnet', 'BARNET', '0044', 'Audley Rd No.134 Flat 3', '2-1599'),
  ('01-0047', '01', 'Barnet', 'BARNET', '0047', 'Barford Close No. 8', '2-1535'),
  ('01-0080', '01', 'Barnet', 'BARNET', '0080', 'Edinburgh No. 13', '2-1529'),
  ('08-0280', '08', 'Buckinghamshire', 'BUCKS', '0280', '10 Allonby Way', '2-1516'),
  ('08-0277', '08', 'Buckinghamshire', 'BUCKS', '0277', '14 Western Dene Hazlemere', '2-1584'),
  ('08-0276', '08', 'Buckinghamshire', 'BUCKS', '0276', '236 West Wycombe Road', '2-1328'),
  ('08-0278', '08', 'Buckinghamshire', 'BUCKS', '0278', '57 Topaz Lane', '2-1413'),
  ('08-0285', '08', 'Buckinghamshire', 'BUCKS', '0285', '95 Foskett Way', '2-1731'),
  ('08-0283', '08', 'Buckinghamshire', 'BUCKS', '0283', 'Drake Close No.4', '2-1586'),
  ('08-0271', '08', 'Buckinghamshire', 'BUCKS', '0271', 'Hughenden Avenue No. 15', '2-1562'),
  ('08-0269', '08', 'Buckinghamshire', 'BUCKS', '0269', 'Knights Templar Way No.21', '2-1561'),
  ('08-0266', '08', 'Buckinghamshire', 'BUCKS', '0266', 'Topaz Lane No.2', '2-1505'),
  ('12-0296', '12', 'Cornwall', 'CORNWALL', '0296', 'Cober Cottage', '2-1650'),
  ('12-0294', '12', 'Cornwall', 'CORNWALL', '0294', 'Office - Riverside House - SL', '2-1549'),
  ('12-0300', '12', 'Cornwall', 'CORNWALL', '0300', 'Roskear No. 12', '2-1716'),
  ('12-0301', '12', 'Cornwall', 'CORNWALL', '0301', 'Roskear No. 14', '2-1717'),
  ('12-0299', '12', 'Cornwall', 'CORNWALL', '0299', 'The Birches', '2-1752'),
  ('22-0364', '22', 'Hertfordshire', 'HERTFORDSHIRE', '0364', '1 Bishops Close', '2-1184'),
  ('22-0430', '22', 'Hertfordshire', 'HERTFORDSHIRE', '0430', '1 Lower Barn', '2-1665'),
  ('22-0358', '22', 'Hertfordshire', 'HERTFORDSHIRE', '0358', '107 Shearwater', '2-1460'),
  ('22-0386', '22', 'Hertfordshire', 'HERTFORDSHIRE', '0386', '2 City Point', '2-1139'),
  ('22-0463', '22', 'Hertfordshire', 'HERTFORDSHIRE', '0463', '3 Printers Avenue', '2-1263'),
  ('22-0474', '22', 'Hertfordshire', 'HERTFORDSHIRE', '0474', '31 Walker Grove', '2-1216'),
  ('22-0419', '22', 'Hertfordshire', 'HERTFORDSHIRE', '0419', '4 Lavender Close', '2-1338'),
  ('22-0452', '22', 'Hertfordshire', 'HERTFORDSHIRE', '0452', '43a Napsbury Lane', '2-1199'),
  ('22-0366', '22', 'Hertfordshire', 'HERTFORDSHIRE', '0366', '5 Baylie', '2-1382'),
  ('22-0398', '22', 'Hertfordshire', 'HERTFORDSHIRE', '0398', '96 Eddington Crescent', '2-1551'),
  ('22-0380', '22', 'Hertfordshire', 'HERTFORDSHIRE', '0380', 'Campion Road No. 36', '2-1610'),
  ('22-0377', '22', 'Hertfordshire', 'HERTFORDSHIRE', '0377', 'Chelwood Ave No.42', '2-1592'),
  ('22-0408', '22', 'Hertfordshire', 'HERTFORDSHIRE', '0408', 'Ganders Ash No 55', '2-1351'),
  ('22-0444', '22', 'Hertfordshire', 'HERTFORDSHIRE', '0444', 'Onslow Close No. 21', '2-1643'),
  ('22-0453', '22', 'Hertfordshire', 'HERTFORDSHIRE', '0453', 'Poplars Close No. 29', '2-1629'),
  ('22-0402', '22', 'Hertfordshire', 'HERTFORDSHIRE', '0402', 'Welbent', '2-1542'),
  ('22-0476', '22', 'Hertfordshire', 'HERTFORDSHIRE', '0476', 'Wood Lane End No.108', '2-1571'),
  ('25-0494', '25', 'Gloucestershire', 'GLOUCOXF', '0494', 'Lauriston Park No. 26', '2-1578'),
  ('25-0492', '25', 'Gloucestershire', 'GLOUCOXF', '0492', 'The Park No. 104', '2-1518'),
  ('36-0553', '36', 'Kent', 'KENT', '0553', '18 Bramling Crescent', '2-1380'),
  ('36-0647', '36', 'Kent', 'KENT', '0647', '22 Pinewood close', '2-1704'),
  ('36-0562', '36', 'Kent', 'KENT', '0562', '25A Blackthorne Avenue', '2-1347'),
  ('36-0573', '36', 'Kent', 'KENT', '0573', '25B Blackthorn Avenue', '2-1348'),
  ('36-0584', '36', 'Kent', 'KENT', '0584', '25C Blackthorn Avenue', '2-1356'),
  ('36-0628', '36', 'Kent', 'KENT', '0628', '3 Sheridan Court', '2-1195'),
  ('36-0551', '36', 'Kent', 'KENT', '0551', 'Auckland Road', '2-1311'),
  ('36-0589', '36', 'Kent', 'KENT', '0589', 'Bramling Crescent No. 28', '2-1504'),
  ('36-0619', '36', 'Kent', 'KENT', '0619', 'Park Road No. 3', '2-1510'),
  ('36-0639', '36', 'Kent', 'KENT', '0639', 'Sheridan Court No 5', '2-1214'),
  ('36-0645', '36', 'Kent', 'KENT', '0645', 'Taylor Close No 7', '2-1570'),
  ('36-0640', '36', 'Kent', 'KENT', '0640', 'Teise Close No.18', '2-1520'),
  ('36-0643', '36', 'Kent', 'KENT', '0643', 'Violet Place No.10', '2-1568'),
  ('50-0679', '50', 'London', NULL, '0679', 'Hendon Office', '2-1502'),
  ('57-0685', '57', 'Manchester', 'MANCHESTER', '0685', 'Regent Avenue No. 17', '2-1611'),
  ('71-0720', '71', 'Northamptonshire', 'NORTHANTS', '0720', '76 Rushton Road', '2-1375'),
  ('71-0722', '71', 'Northamptonshire', 'NORTHANTS', '0722', 'Meadway No. 2', '2-1668'),
  ('71-0721', '71', 'Northamptonshire', 'NORTHANTS', '0721', 'Tiverton Avenue No. 23', '2-1667'),
  ('80-0793', '80', 'Luton', NULL, '0793', '23 Torquay Drive', '2-1366'),
  ('82-0810', '82', 'Oxfordshire', 'GLOUCOXF', '0810', '55 Cherry Tree Way', '2-1420');

CREATE INDEX IF NOT EXISTS idx_service_location_staffrota ON service_location(staffrota_region);
CREATE INDEX IF NOT EXISTS idx_service_location_region_code ON service_location(region_code);
