-- V022: bridge staffrota location strings onto the service_location master.
ALTER TABLE service_location ADD COLUMN IF NOT EXISTS staffrota_location varchar(80);

BEGIN;
UPDATE service_location SET staffrota_location=NULL;
UPDATE service_location SET staffrota_location='13 EDINBURG' WHERE external_id='01-0080';
UPDATE service_location SET staffrota_location='20 GLEBE' WHERE external_id='01-0111';
UPDATE service_location SET staffrota_location='29 EDGEWORTH' WHERE external_id='01-0082';
UPDATE service_location SET staffrota_location='3 HIGHFIELDS' WHERE external_id='01-0144';
UPDATE service_location SET staffrota_location='4 AUDLEY' WHERE external_id='01-0050';
UPDATE service_location SET staffrota_location='57 STURGESS' WHERE external_id='01-0177';
UPDATE service_location SET staffrota_location='61 VICTORIA' WHERE external_id='01-0212';
UPDATE service_location SET staffrota_location='8 BARFORD' WHERE external_id='01-0047';
UPDATE service_location SET staffrota_location='9 CLAYDON' WHERE external_id='01-0056';
UPDATE service_location SET staffrota_location='FLAT 2 AUDLEY' WHERE external_id='01-0045';
UPDATE service_location SET staffrota_location='GOLDERS RISE' WHERE external_id='01-0122';
UPDATE service_location SET staffrota_location='RIVERDALE' WHERE external_id='01-0155';
UPDATE service_location SET staffrota_location='10 Allonby Way' WHERE external_id='08-0280';
UPDATE service_location SET staffrota_location='14 Western Dene Road' WHERE external_id='08-0277';
UPDATE service_location SET staffrota_location='2 Topaz Lane' WHERE external_id='08-0266';
UPDATE service_location SET staffrota_location='21 Knight''s Templar Way' WHERE external_id='08-0269';
UPDATE service_location SET staffrota_location='95 Foskett Way' WHERE external_id='08-0285';
UPDATE service_location SET staffrota_location='Drake Close' WHERE external_id='08-0283';
UPDATE service_location SET staffrota_location='Hughenden' WHERE external_id='08-0271';
UPDATE service_location SET staffrota_location='Cober Cottage' WHERE external_id='12-0296';
UPDATE service_location SET staffrota_location='Roskear' WHERE external_id='12-0300';
UPDATE service_location SET staffrota_location='The Birches' WHERE external_id='12-0299';
UPDATE service_location SET staffrota_location='26 Lauriston Park' WHERE external_id='25-0494';
UPDATE service_location SET staffrota_location='Cherry Tree' WHERE external_id='82-0810';
UPDATE service_location SET staffrota_location='BAYLIE LANE' WHERE external_id='22-0366';
UPDATE service_location SET staffrota_location='BISHOPS' WHERE external_id='22-0364';
UPDATE service_location SET staffrota_location='CAMPION' WHERE external_id='22-0380';
UPDATE service_location SET staffrota_location='CHELWOOD' WHERE external_id='22-0377';
UPDATE service_location SET staffrota_location='CITY POINT' WHERE external_id='22-0386';
UPDATE service_location SET staffrota_location='EDDINGTON' WHERE external_id='22-0398';
UPDATE service_location SET staffrota_location='LAVENDER' WHERE external_id='22-0419';
UPDATE service_location SET staffrota_location='LOWER BARN' WHERE external_id='22-0430';
UPDATE service_location SET staffrota_location='NAPSBURY' WHERE external_id='22-0452';
UPDATE service_location SET staffrota_location='ONSLOW' WHERE external_id='22-0444';
UPDATE service_location SET staffrota_location='POPLARS' WHERE external_id='22-0453';
UPDATE service_location SET staffrota_location='PRINTERS' WHERE external_id='22-0463';
UPDATE service_location SET staffrota_location='SHEARWATER' WHERE external_id='22-0358';
UPDATE service_location SET staffrota_location='WALKER' WHERE external_id='22-0474';
UPDATE service_location SET staffrota_location='WELBENT' WHERE external_id='22-0402';
UPDATE service_location SET staffrota_location='WOOD LANE END' WHERE external_id='22-0476';
UPDATE service_location SET staffrota_location='AUCKLAND' WHERE external_id='36-0551';
UPDATE service_location SET staffrota_location='BLACKTHORN A' WHERE external_id='36-0562';
UPDATE service_location SET staffrota_location='BRAMLING 18' WHERE external_id='36-0553';
UPDATE service_location SET staffrota_location='BRAMLING 28' WHERE external_id='36-0589';
UPDATE service_location SET staffrota_location='PINEWOOD' WHERE external_id='36-0647';
UPDATE service_location SET staffrota_location='TAYLOR CLOSE' WHERE external_id='36-0645';
UPDATE service_location SET staffrota_location='VIOLET PLACE' WHERE external_id='36-0643';
UPDATE service_location SET staffrota_location='17 Regent Avenue' WHERE external_id='57-0685';
UPDATE service_location SET staffrota_location='MEADWAY' WHERE external_id='71-0722';
UPDATE service_location SET staffrota_location='RUSHTON' WHERE external_id='71-0720';
UPDATE service_location SET staffrota_location='TIVERTON' WHERE external_id='71-0721';
UPDATE service_location SET staffrota_location='1ST AVENUE' WHERE external_id='01-0089';
UPDATE service_location SET staffrota_location='17A AVENUE' WHERE external_id='01-0090';
UPDATE service_location SET staffrota_location='104 The Park' WHERE external_id='25-0492';
COMMIT;
